services:
  # Backend Service (API + Frontend)
  - type: web
    name: equipment-app
    env: node
    plan: free
    sourceDir: .
    buildCommand: |
      cd backend
      npm install
      npm run build
      cd ../frontend
      npm install
      npm run build
      cd ../backend
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: equipment-db
          property: connectionString
      - key: PORT
        value: 10000

databases:
  - name: equipment-db
    databaseName: equipment_db
    user: equipment_user
    plan: free 