services:
  # Backend Service
  - type: web
    name: equipment-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: equipment-db
          property: connectionString
      - key: PORT
        value: 10000

  # Frontend Service
  - type: web
    name: equipment-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://equipment-backend.onrender.com

databases:
  - name: equipment-db
    databaseName: equipment_db
    user: equipment_user
    plan: free 